Make two minor updates to example target data
Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub pull request #26
Opened 2024-04-02 20:55 UTC by bsweger

Resolves #4

Use "NA" instead of "*" for quantile output type and rename the "value" column to "observation"

2024-04-02 20:56 UTC, bsweger commented on target-data/target-values.csv
@elray1 Do you think we should rename the file too? (e.g., `target-observations.csv`)

2024-04-03 16:57 UTC, elray1 requested changes
yes, let's change the name of the file to target-observations.csv

2024-04-03 17:31 UTC, bsweger commented
@elray1 Just pushed a commit to rename the file. Let's do a "squash and merge" on this (I'm happy to do the honors once you've approved).

2024-04-03 17:40 UTC, elray1 approved these changes

2024-04-03 17:48 UTC, merged